import { supabase } from "./supabase/client.js";

const students=["Aditya Pratama","Ahmad Fauzan","Aldi Saputra","Andika Wijaya","Bagas Ramadhan","Bima Setiawan","Cahyo Nugroho","Daffa Nurkhalish","Dani Kurniawan","Dimas Saputra","Fajar Ramadhan","Fauzan Akbar","Galang Pratama","Hafiz Maulana","Ilham Saputra","Joko Susanto","Kevin Alvaro","Lukman Hakim","M. Rizky","M. Fadli","Nanda Putra","Naufal Ramadhan","Noval Ardiansyah","Putra Wijaya","Raka Aditya","Rangga Saputra","Reza Fahlevi","Rizal Maulana","Salsa Putri","Siti Aisyah","Tasya Amelia","Vina Lestari","Wahyu Hidayat","Yogi Prasetyo","Zaki Ramadhan","Zulfan Akbar"];
const schedules={senin:[["07:00","08:30","Bahasa Indonesia","Bapak/Ibu Guru","X APAT 1"],["08:30","10:00","Matematika","Bapak/Ibu Guru","X APAT 1"],["10:15","11:45","Produktif APAT","Bapak/Ibu Guru","Lab APAT"],["12:30","14:00","Pendidikan Agama","Bapak/Ibu Guru","X APAT 1"]],selasa:[["07:00","08:30","Bahasa Inggris","Bapak/Ibu Guru","X APAT 1"],["08:30","10:00","Produktif APAT","Bapak/Ibu Guru","Lab APAT"],["10:15","11:45","IPAS","Bapak/Ibu Guru","X APAT 1"],["12:30","14:00","PJOK","Bapak/Ibu Guru","Lapangan"]],rabu:[["07:00","08:30","Matematika","Bapak/Ibu Guru","X APAT 1"],["08:30","10:00","Bahasa Inggris","Bapak/Ibu Guru","X APAT 1"],["10:15","11:45","Produktif APAT","Bapak/Ibu Guru","Lab APAT"],["12:30","14:00","Sejarah","Bapak/Ibu Guru","X APAT 1"]],kamis:[["07:00","08:30","Bahasa Indonesia","Bapak/Ibu Guru","X APAT 1"],["08:30","10:00","Produktif APAT","Bapak/Ibu Guru","Lab APAT"],["10:15","11:45","Pendidikan Pancasila","Bapak/Ibu Guru","X APAT 1"],["12:30","14:00","Seni Budaya","Bapak/Ibu Guru","X APAT 1"]],jumat:[["07:00","08:30","Pendidikan Agama","Bapak/Ibu Guru","X APAT 1"],["08:30","10:00","Bahasa Inggris","Bapak/Ibu Guru","X APAT 1"],["10:15","11:45","Produktif APAT","Bapak/Ibu Guru","Lab APAT"]]};
const names={senin:"Senin",selasa:"Selasa",rabu:"Rabu",kamis:"Kamis",jumat:"Jumat"},keys=Object.keys(names);
const duty={senin:["Aditya Pratama","Daffa Nurkhalish","Fajar Ramadhan","Galang Pratama","Hafiz Maulana","Rizal Maulana","Salsa Putri"],selasa:["Ahmad Fauzan","Bima Setiawan","Dani Kurniawan","Ilham Saputra","Nanda Putra","Tasya Amelia","Wahyu Hidayat"],rabu:["Aldi Saputra","Bagas Ramadhan","Dimas Saputra","Joko Susanto","Naufal Ramadhan","Vina Lestari","Yogi Prasetyo"],kamis:["Andika Wijaya","Cahyo Nugroho","Fauzan Akbar","Kevin Alvaro","Noval Ardiansyah","Raka Aditya","Zaki Ramadhan"],jumat:["M. Rizky","M. Fadli","Lukman Hakim","Putra Wijaya","Reza Fahlevi","Siti Aisyah"]};
const announcements=[["Selamat Datang di CLASSHUB","CLASSHUB menjadi pusat informasi digital untuk seluruh anggota X APAT 1.","14 Agustus 2026"],["Persiapan Kegiatan Kelas","Mohon seluruh siswa memperhatikan informasi kegiatan kelas yang akan datang.","14 Agustus 2026"],["Jaga Kebersihan Kelas","Jangan lupa melaksanakan jadwal piket sesuai pembagian masing-masing.","13 Agustus 2026"]];
const initials=n=>{let a=n.split(" ");return (a.length>1?a[0][0]+a[1][0]:a[0].slice(0,2)).toUpperCase()};
const today=()=>({1:"senin",2:"selasa",3:"rabu",4:"kamis",5:"jumat"}[new Date().getDay()]||"senin");
const esc=s=>s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));

function updateClock(){const d=new Date(),h=d.getHours();document.getElementById("date").textContent=d.toLocaleDateString("id-ID",{weekday:"long",day:"numeric",month:"long",year:"numeric"});document.getElementById("time").textContent=d.toLocaleTimeString("id-ID",{hour:"2-digit",minute:"2-digit",second:"2-digit"})+" WIB";document.getElementById("greeting").textContent=(h<11?"☀ SELAMAT PAGI":h<15?"☀ SELAMAT SIANG":h<18?"☀ SELAMAT SORE":"☾ SELAMAT MALAM")+" • CLASS MANAGEMENT SYSTEM"}updateClock();setInterval(updateClock,1000);

function renderStudents(list){const g=document.getElementById("studentsGrid");g.innerHTML=list.map((n,i)=>`<article class="student"><i class="avatar">${initials(n)}</i><div><h4>${esc(n)}</h4><p>X APAT 1 · Siswa</p></div><span class="num">${String(i+1).padStart(2,"0")}</span></article>`).join("");document.getElementById("result").textContent=list.length;document.getElementById("empty").classList.toggle("show",list.length===0)}
renderStudents(students);
const input=document.getElementById("search"),clear=document.getElementById("clear");input.addEventListener("input",()=>{const q=input.value.toLowerCase().trim();renderStudents(students.filter(n=>n.toLowerCase().includes(q)));clear.style.display=q?"block":"none"});clear.onclick=()=>{input.value="";input.dispatchEvent(new Event("input"));input.focus()};

function renderSchedule(k){const d=schedules[k];document.getElementById("dayTitle").textContent=names[k];document.getElementById("schedCount").textContent=d.length;document.getElementById("scheduleList").innerHTML=d.map(x=>`<div class="scheduleRow"><time><b>${x[0]}</b><small>${x[1]}</small></time><i class="dot"></i><div class="subject"><b>${x[2]}</b><small>${x[3]}</small></div><span class="room">${x[4]}</span></div>`).join("")}
document.getElementById("days").innerHTML=keys.map(k=>`<button class="day" data-day="${k}"><b>${names[k].slice(0,3)}</b><small>${names[k]}</small></button>`).join("");document.querySelectorAll(".day").forEach(b=>b.onclick=()=>{document.querySelectorAll(".day").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderSchedule(b.dataset.day)});document.querySelector(`[data-day="${today()}"]`).classList.add("active");renderSchedule(today());

document.getElementById("dashAnnouncements").innerHTML=announcements.slice(0,2).map(a=>`<div class="announcement"><h4>${a[0]}</h4><p>${a[1]}</p><small>${a[2]}</small></div>`).join("");
document.getElementById("announceList").innerHTML=announcements.map(a=>`<article class="largeAnn"><span class="badge">INFO</span><h2>${a[0]}</h2><p>${a[1]}</p><div class="meta"><i class="fa-regular fa-calendar"></i> ${a[2]} · Admin Kelas</div></article>`).join("");

function renderDashboard(){const k=today(),d=schedules[k],arr=duty[k];document.getElementById("todayCount").textContent=d.length;document.getElementById("dutyCount").textContent=arr.length;document.getElementById("dashSchedule").innerHTML=d.map(x=>`<div class="minirow"><time><b>${x[0]}</b><small>${x[1]}</small></time><i class="dot"></i><div><strong>${x[2]}</strong><p>${x[3]}</p></div></div>`).join("");document.getElementById("dashDuty").innerHTML=arr.map(n=>`<div class="person"><i>${initials(n)}</i><b>${n}</b></div>`).join("");document.getElementById("dutyGrid").innerHTML=keys.map(day=>`<article class="dutyday ${day===k?"today":""}"><div class="dutyhead"><h3>${names[day]}</h3>${day===k?'<span class="today">HARI INI</span>':""}</div>${duty[day].map(n=>`<div class="dutyitem"><i>${initials(n)}</i><b>${n}</b></div>`).join("")}</article>`).join("")}renderDashboard();

const titles={dashboard:"Dashboard",students:"Daftar Siswa",schedule:"Jadwal Pelajaran",announcements:"Pengumuman",duty:"Jadwal Piket",about:"Tentang"};
function go(page){document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id===page));document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n.dataset.page===page));document.getElementById("pageTitle").textContent=titles[page];closeMenu();window.scrollTo({top:0,behavior:"smooth"})}
document.querySelectorAll(".nav").forEach(n=>n.onclick=()=>go(n.dataset.page));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>go(b.dataset.go));

const side=document.getElementById("sidebar"),back=document.getElementById("backdrop");function closeMenu(){side.classList.remove("open");back.classList.remove("show")}document.getElementById("menuBtn").onclick=()=>{side.classList.add("open");back.classList.add("show")};back.onclick=closeMenu;

const modal=document.getElementById("modal");document.getElementById("adminBtn").onclick=()=>modal.classList.add("show");document.getElementById("closeModal").onclick=()=>modal.classList.remove("show");modal.onclick=e=>{if(e.target===modal)modal.classList.remove("show")};
function showToast(t){modal.classList.remove("show");const el=document.getElementById("toast");el.textContent=t+" siap dikembangkan.";el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
